CREATE DEFINER=`root`@`localhost` PROCEDURE `CRUD_USUARIO`(IN jsonData JSON)
BEGIN
	DECLARE ACAO CHAR;
    DECLARE ID_USUARIO INT;
    DECLARE NOME VARCHAR(100);
    DECLARE CPF VARCHAR(100);
    DECLARE RG VARCHAR(100);
    DECLARE EMAIL VARCHAR(100);
    DECLARE DATA_NASCIMENTO DATE;
    DECLARE TELEFONE VARCHAR(100);
    DECLARE SENHA VARCHAR(100);

    SET ACAO = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.ACAO'));
    SET ID_USUARIO = CAST(JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.ID_USUARIO')) AS UNSIGNED);
    SET NOME = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.NOME'));
    SET CPF = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.CPF'));
    SET RG = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.RG'));
    SET EMAIL = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.EMAIL'));
    SET DATA_NASCIMENTO = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.DATA_NASCIMENTO'));
    SET TELEFONE = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.TELEFONE'));
    SET SENHA = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.SENHA'));

    IF ACAO = 'C' THEN 
        INSERT INTO USUARIO(NOME, CPF, RG, EMAIL, DATA_NASCIMENTO, TELEFONE, SENHA)
        VALUES (NOME, CPF, RG, EMAIL, DATA_NASCIMENTO, TELEFONE, SENHA);
    ELSEIF ACAO = 'U' THEN 
        UPDATE USUARIO SET 
            NOME = NOME,
            CPF = CPF,
            RG = RG,
            EMAIL = EMAIL,
            DATA_NASCIMENTO = DATA_NASCIMENTO,
            TELEFONE = TELEFONE,
            SENHA = SENHA
        WHERE ID_USUARIO = ID_USUARIO;
    ELSEIF ACAO = 'D' THEN 
        DELETE FROM USUARIO WHERE ID_USUARIO = ID_USUARIO;
    ELSEIF ACAO = 'R' THEN 
        SELECT * FROM USUARIO WHERE ID_USUARIO = ID_USUARIO;
    ELSEIF ACAO = 'S' THEN 
        SELECT * FROM USUARIO;
    END IF;
END