CREATE PROCEDURE `CRUD_ADM`(IN jsonData JSON)
BEGIN
    DECLARE _ACAO CHAR(1);
    DECLARE _ID_ADM INT;
    DECLARE _NOME VARCHAR(50);
    DECLARE _EMAIL VARCHAR(254);
    DECLARE _TELEFONE VARCHAR(20);
    DECLARE _SENHA VARCHAR(255);
    DECLARE _CAMINHO_FOTO VARCHAR(100);

    DECLARE _CODIGO_ERRO INT;
    DECLARE _ERRO_MSG VARCHAR(255);

    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
    BEGIN
        GET DIAGNOSTICS CONDITION 1
            _CODIGO_ERRO = MYSQL_ERRNO, _ERRO_MSG = MESSAGE_TEXT;

        SET _ERRO_MSG = CONCAT('Erro na linha: ', _CODIGO_ERRO, ' Mensagem: ', _ERRO_MSG);

        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = _ERRO_MSG;
    END;

    SET _ACAO = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.ACAO'));
    SET _ID_ADM = CAST(JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.ID_ADM')) AS UNSIGNED);
    SET _NOME = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.NOME'));
    SET _EMAIL = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.EMAIL'));
    SET _TELEFONE = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.TELEFONE'));
    SET _SENHA = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.SENHA'));
    SET _CAMINHO_FOTO = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.CAMINHO_FOTO'));

    IF _ACAO = 'C' THEN 
        INSERT INTO ADM(NOME, EMAIL, TELEFONE, SENHA)
        VALUES(_NOME, _EMAIL, _TELEFONE, _SENHA);

        SET _ID_ADM = LAST_INSERT_ID();

        IF JSON_LENGTH(JSON_EXTRACT(jsonData, '$.CAMINHO_FOTO')) > 0 THEN
            DECLARE i INT DEFAULT 0;
            DECLARE total INT;

            SET total = JSON_LENGTH(JSON_EXTRACT(jsonData, '$.FOTOS'));

            WHILE i < total DO
                SET _CAMINHO_FOTO = JSON_UNQUOTE(JSON_EXTRACT(jsonData, CONCAT('$.FOTOS[', i, ']')));
                INSERT INTO PHOTOS(ID_ADM, CAMINHO_FOTO) VALUES (_ID_ADM, _CAMINHO_FOTO);
                SET i = i + 1;
            END WHILE;
        END IF;

    ELSEIF _ACAO = 'U' THEN
        UPDATE ADM SET 
            NOME = _NOME,
            EMAIL = _EMAIL,
            TELEFONE = _TELEFONE,
            SENHA = _SENHA
        WHERE ID_ADM = _ID_ADM;

    ELSEIF _ACAO = 'D' THEN
        DELETE FROM ADM 
        WHERE ID_ADM = _ID_ADM;

    ELSEIF _ACAO = 'R' THEN
        SELECT * FROM ADM 
        WHERE 1 = 1
        AND (_ID_ADM IS NULL OR ID_ADM = _ID_ADM)
        AND (_EMAIL IS NULL OR EMAIL = _EMAIL);

    ELSEIF _ACAO = 'G' THEN
        CREATE TEMPORARY TABLE GRID_COLUNA(
            ID_COL VARCHAR(100),
            NM_COL VARCHAR(100)
        );

        INSERT INTO GRID_COLUNA(ID_COL, NM_COL)
        VALUES  ('NOME', 'Nome'),
                ('EMAIL', 'Email'),
                ('TELEFONE', 'Telefone');

        SELECT * FROM GRID_COLUNA;
    END IF;
END
