CREATE DEFINER=`root`@`localhost` PROCEDURE `CRUD_EVENTO`(IN jsonData JSON)
BEGIN 
    DECLARE ACAO CHAR;
    DECLARE ID_EVENTO INT PRIMARY KEY AUTO_INCREMENT;
    DECLARE TITULO VARCHAR(100);
    DECLARE DESCRICAO VARCHAR(100);
    DECLARE CIDADE_ESTADO VARCHAR(100);
    DECLARE LOCAL_EVENTO VARCHAR(100);

    SET ACAO = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.ACAO'));
    SET ID_EVENTO = CAST(JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.ID_EVENTO')) AS UNSIGNED);
    SET TITULO = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.TITULO'));
    SET DESCRICAO = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.DESCRICAO'));
    SET CIDADE_ESTADO = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.CIDADE_ESTADO'));
    SET LOCAL_EVENTO = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.LOCAL_EVENTO'));

    IF ACAO = 'C' THEN
        INSERT INTO EVENTO(TITULO, DESCRICAO, CIDADE_ESTADO, LOCAL_EVENTO)
        VALUES (TITULO, DESCRICAO, CIDADE_ESTADO, LOCAL_EVENTO);
    ELSEIF ACAO = 'U' THEN 
        UPDATE EVENTO SET 
            TITULO = TITULO,
            DESCRICAO = DESCRICAO,
            CIDADE_ESTADO = CIDADE_ESTADO,
            LOCAL_EVENTO = LOCAL_EVENTO
        WHERE ID_EVENTO = ID_EVENTO;
    ELSEIF ACAO = 'D' THEN
        DELETE FROM EVENTO WHERE ID_EVENTO = ID_EVENTO;
    ELSEIF ACAO = 'R' THEN
        SELECT * FROM EVENTO WHERE ID_EVENTO = ID_EVENTO;
    ELSEIF ACAO = 'S' THEN 
        SELECT * FROM EVENTO;
    END IF;
END