CREATE PROCEDURE `CRUD_ADM`(IN jsonData JSON)
BEGIN
	DECLARE ACAO CHAR;
    DECLARE ID_ADM INT;
    DECLARE NOME VARCHAR(100);
    DECLARE EMAIL VARCHAR(100);
    DECLARE TELEFONE VARCHAR(100);
    DECLARE SENHA VARCHAR(100);

    SET ACAO = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.ACAO'));
    SET ID_ADM = CAST(JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.ID_ADM')) AS UNSIGNED);
    SET NOME = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.NOME'));
    SET EMAIL = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.EMAIL'));
    SET TELEFONE = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.TELEFONE'));
    SET SENHA = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.SENHA'));

    IF ACAO = 'C' THEN 
        INSERT INTO MEMBRO_ADM(NOME, EMAIL, TELEFONE, SENHA)
        VALUES(NOME, EMAIL, TELEFONE, SENHA);
	ELSEIF ACAO = 'U' THEN
		UPDATE MEMBRO_ADM SET 
			NOME = NOME,
			EMAIL = EMAIL,
			TELEFONE = TELEFONE,
			SENHA = SENHA
		WHERE ID_ADM = ID_ADM;
	ELSEIF ACAO = 'D' THEN
		DELETE FROM MEMBRO_ADM WHERE ID_ADM = ID_ADM;
	ELSEIF ACAO = 'R' THEN
		SELECT * FROM MEMBRO_ADM WHERE ID_ADM = ID_ADM;
	ELSEIF ACAO = 'S' THEN
		SELECT * FROM MEMBRO_ADM;
	END IF;
END