CREATE DEFINER=`root`@`localhost` PROCEDURE `CRUD_FORMULARIO_PERGUNTA`(IN jsonData JSON)
BEGIN
	DECLARE ACAO CHAR;
    DECLARE ID_FORMULARIO_PERGUNTA INT;
    DECLARE DS_FORMULARIO_PERGUNTA VARCHAR(100);

    SET ACAO = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.ACAO'));
    SET ID_FORMULARIO_PERGUNTA = CAST(JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.ID_FORMULARIO_PERGUNTA')) AS UNSIGNED);
    SET DS_FORMULARIO_PERGUNTA = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.DS_FORMULARIO_PERGUNTA')); 

    IF ACAO = 'C' THEN 
        INSERT INTO FORMULARIO_PERGUNTA(DS_FORMULARIO_PERGUNTA)
        VALUES(DS_FORMULARIO_PERGUNTA);
    ELSEIF ACAO = 'U' THEN 
        UPDATE FORMULARIO_PERGUNTA SET 
            DS_FORMULARIO_PERGUNTA = DS_FORMULARIO_PERGUNTA
        WHERE ID_FORMULARIO_PERGUNTA = ID_FORMULARIO_PERGUNTA;
    ELSEIF ACAO = 'D' THEN 
        DELETE FROM FORMULARIO_PERGUNTA WHERE ID_FORMULARIO_PERGUNTA = ID_FORMULARIO_PERGUNTA;
    ELSEIF ACAO = 'R' THEN 
        SELECT * FROM FORMULARIO_PERGUNTA WHERE ID_FORMULARIO_PERGUNTA = ID_FORMULARIO_PERGUNTA;
    ELSEIF ACAO = 'S' THEN 
        SELECT * FROM FORMULARIO_PERGUNTA;
    END IF;
END