CREATE DEFINER=`root`@`localhost` PROCEDURE `CRUD_TAG`(IN jsonData JSON)
BEGIN
	DECLARE ACAO CHAR;
    DECLARE ID_TAG INT;
    DECLARE DS_TAG VARCHAR(100);

    SET ACAO = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.ACAO'));
    SET ID_TAG = CAST(JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.ID_TAG')) AS UNSIGNED);
    SET DS_TAG = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.DS_TAG')); 

    IF ACAO = 'C' THEN 
        INSERT INTO TAG(DS_TAG)
        VALUES(DS_TAG);
    ELSEIF ACAO = 'U' THEN 
        UPDATE TAG SET 
            DS_TAG = DS_TAG
        WHERE ID_TAG = ID_TAG;
    ELSEIF ACAO = 'D' THEN 
        DELETE FROM TAG WHERE ID_TAG = ID_TAG;
    ELSEIF ACAO = 'R' THEN 
        SELECT * FROM TAG WHERE ID_TAG = ID_TAG;
    ELSEIF ACAO = 'S' THEN 
        SELECT * FROM TAG;
    END IF;
END