CREATE PROCEDURE `CRUD_FOTO`(IN jsonData JSON)
BEGIN
	DECLARE _ACAO CHAR;
    DECLARE _ID_FOTO INT;
    DECLARE _ID_OBJ INT;
    DECLARE _ID_TIPO_OBJ INT;
    DECLARE _CAMINHO_FOTO TEXT;

    DECLARE i INT DEFAULT 0;
    DECLARE total INT;

    SET ACAO = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.ACAO'));
    SET _ID_FOTO = CAST(JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.ID_FOTO')) AS UNSIGNED);
    SET _ID_OBJ = CAST(JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.ID_OBJ')) AS UNSIGNED);
    SET _ID_TIPO_OBJ = CAST(JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.ID_TIPO_OBJ')) AS UNSIGNED);

    IF ACAO = 'C' THEN 
        SET total = JSON_LENGTH(JSON_EXTRACT(jsonData, '$.CAMINHO_FOTO'));
		WHILE i < total DO
			INSERT INTO FOTO (ID_OBJ, ID_TIPO_OBJ, CAMINHO_FOTO)
			VALUES (
				_ID_OBJ,
				_ID_TIPO_OBJ,
				JSON_UNQUOTE(JSON_EXTRACT(jsonData, CONCAT('$.CAMINHO_FOTO[', i, ']')))
			);
			SET i = i + 1;
		END WHILE;
    ELSEIF ACAO = 'U' THEN 
        
    ELSEIF ACAO = 'D' THEN 
        DELETE FROM FOTO
        WHERE ID_FOTO = _ID_FOTO;
    ELSEIF ACAO = 'R' THEN 
        SELECT * 
        FROM FOTO 
        WHERE ID_FOTO = _ID_FOTO 
            AND ID_OBJ = _ID_OBJ
            AND ID_TIPO_OBJ = _ID_TIPO_OBJ;
    END IF;
END