CREATE DEFINER=`root`@`localhost` PROCEDURE `CRUD_EVENTO`(IN jsonData JSON)
BEGIN 
    DECLARE _ACAO CHAR;
    DECLARE _ID_EVENTO INT;
    DECLARE _TITULO VARCHAR(100);
    DECLARE _DESCRICAO TEXT;
    DECLARE _CIDADE VARCHAR(50);
    DECLARE _ESTADO VARCHAR(2);
    DECLARE _LOCAL_EVENTO VARCHAR(100);

    DECLARE _CODIGO_ERRO INT;
    DECLARE _ERRO_MSG VARCHAR(255);

    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
    BEGIN
        GET DIAGNOSTICS CONDITION 1
            _CODIGO_ERRO = MYSQL_ERRNO, _ERRO_MSG = MESSAGE_TEXT;

        SET _ERRO_MSG = CONCAT('Erro na linha: ', _CODIGO_ERRO, ' Mensagem: ', _ERRO_MSG);

        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = _ERRO_MSG;
    END;

    SET _ACAO = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.ACAO'));
    SET _ID_EVENTO = CAST(JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.ID_EVENTO')) AS UNSIGNED);
    SET _TITULO = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.TITULO'));
    SET _DESCRICAO = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.DESCRICAO'));
    SET _CIDADE = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.CIDADE'));
    SET _ESTADO = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.ESTADO'));
    SET _LOCAL_EVENTO = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.LOCAL_EVENTO'));

    IF _ACAO = 'C' THEN
        INSERT INTO EVENTO(TITULO, DESCRICAO, CIDADE, ESTADO, LOCAL_EVENTO)
        VALUES (_TITULO, _DESCRICAO, _CIDADE, _ESTADO, _LOCAL_EVENTO);

    ELSEIF _ACAO = 'U' THEN 
        UPDATE EVENTO SET 
            TITULO = _TITULO,
            DESCRICAO = _DESCRICAO,
            CIDADE = _CIDADE,
            ESTADO = _ESTADO,
            LOCAL_EVENTO = _LOCAL_EVENTO
        WHERE ID_EVENTO = _ID_EVENTO;

    ELSEIF _ACAO = 'D' THEN
        DELETE FROM EVENTO 
        WHERE ID_EVENTO = _ID_EVENTO;

    ELSEIF _ACAO = 'R' THEN
        SELECT * FROM EVENTO 
        WHERE 1 = 1 
            AND (_ID_EVENTO IS NULL OR ID_EVENTO = _ID_EVENTO);

    ELSEIF _ACAO = 'G' THEN
        CREATE TEMPORARY TABLE GRID_COLUNA(
            ID_COL VARCHAR(100),
            NM_COL VARCHAR(100)
        );

        INSERT INTO GRID_COLUNA(ID_COL, NM_COL)
        VALUES  ('TITULO', 'Titulo'),
                ('DESCRICAO', 'Descrição'),
                ('CIDADE', 'Cidade'),
                ('ESTADO', 'Estado'),
                ('LOCAL_EVENTO', 'Local do Evento');

        SELECT * FROM GRID_COLUNA;
    END IF;
END