CREATE DEFINER=`root`@`localhost` PROCEDURE `CRUD_ANIMAL`(IN jsonData JSON)
BEGIN
	DECLARE ACAO CHAR;
    DECLARE ID_ANIMAL INT;
    DECLARE NOME VARCHAR(100);
    DECLARE TIPO_ANIMAL VARCHAR(50);
    DECLARE RACA VARCHAR(100);
    DECLARE PORTE VARCHAR(7);
    DECLARE IDADE VARCHAR(11);
    DECLARE DESCRICAO VARCHAR(255);
    DECLARE SEXO VARCHAR(5);
    
    SET ACAO = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.ACAO'));
    SET ID_ANIMAL = CAST(JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.ID_ANIMAL')) AS UNSIGNED);
    SET NOME = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.NOME'));
    SET TIPO_ANIMAL = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.TIPO_ANIMAL'));
    SET RACA = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.RACA'));
    SET PORTE = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.PORTE'));
    SET IDADE = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.IDADE'));
    SET DESCRICAO = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.DESCRICAO'));
    SET SEXO = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.SEXO'));
    
    IF ACAO = 'C' THEN
		INSERT INTO ANIMAL(NOME, TIPO_ANIMAL, RACA, PORTE, IDADE, DESCRICAO, SEXO)
        VALUES(NOME, TIPO_ANIMAL, RACA, PORTE, IDADE, DESCRICAO, SEXO);
	ELSEIF ACAO = 'U' THEN
		UPDATE ANIMAL SET 
			NOME = NOME,
			TIPO_ANIMAL = TIPO_ANIMAL,
			RACA = RACA,
			PORTE = PORTE,
            IDADE = IDADE,
            DESCRICAO = DESCRICAO,
            SEXO = SEXO
		WHERE ID_ANIMAL = ID_ANIMAL;
	ELSEIF ACAO = 'D' THEN
		DELETE FROM ANIMAL WHERE ID_ANIMAL = ID_ANIMAL;
	ELSEIF ACAO = 'R' THEN
		SELECT * FROM ANIMAL WHERE ID_ANIMAL = ID_ANIMAL;
	ELSEIF ACAO = 'S' THEN
		SELECT * FROM ANIMAL;
	END IF;
END