CREATE PROCEDURE `CRUD_ANIMAL`(IN jsonData JSON)
BEGIN
	DECLARE _ACAO CHAR;
    DECLARE _ID_ANIMAL INT;
    DECLARE _NOME VARCHAR(50);
    DECLARE _TIPO_ANIMAL VARCHAR(30);
    DECLARE _RACA VARCHAR(100);
    DECLARE _PORTE VARCHAR(7);
    DECLARE _IDADE VARCHAR(11);
    DECLARE _DESCRICAO TEXT;
    DECLARE _SEXO VARCHAR(5);
    
    DECLARE _CODIGO_ERRO INT;
    DECLARE _ERRO_MSG VARCHAR(255);

    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
    BEGIN
        GET DIAGNOSTICS CONDITION 1
            _CODIGO_ERRO = MYSQL_ERRNO, _ERRO_MSG = MESSAGE_TEXT;

        SET _ERRO_MSG = CONCAT('Erro na linha: ', _CODIGO_ERRO, ' Mensagem: ', _ERRO_MSG);

        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = _ERRO_MSG;
    END;

    SET _ACAO = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.ACAO'));
    SET _ID_ANIMAL = CAST(JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.ID_ANIMAL')) AS UNSIGNED);
    SET _NOME = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.NOME'));
    SET _TIPO_ANIMAL = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.TIPO_ANIMAL'));
    SET _RACA = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.RACA'));
    SET _PORTE = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.PORTE'));
    SET _IDADE = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.IDADE'));
    SET _DESCRICAO = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.DESCRICAO'));
    SET _SEXO = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.SEXO'));
    
    IF _ACAO = 'C' THEN
		INSERT INTO ANIMAL(NOME, TIPO_ANIMAL, RACA, PORTE, IDADE, DESCRICAO, SEXO)
        VALUES(_NOME, _TIPO_ANIMAL, _RACA, _PORTE, _IDADE, _DESCRICAO, _SEXO);

	ELSEIF _ACAO = 'U' THEN
		UPDATE ANIMAL SET 
			NOME = _NOME,
			TIPO_ANIMAL = _TIPO_ANIMAL,
			RACA = _RACA,
			PORTE = _PORTE,
            IDADE = _IDADE,
            DESCRICAO = _DESCRICAO,
            SEXO = _SEXO
		WHERE ID_ANIMAL = _ID_ANIMAL;

	ELSEIF _ACAO = 'D' THEN
		DELETE FROM ANIMAL 
        WHERE ID_ANIMAL = _ID_ANIMAL;

	ELSEIF _ACAO = 'R' THEN
		SELECT * 
        FROM ANIMAL 
        WHERE 1 = 1 
            AND (_ID_ANIMAL IS NULL OR ID_ANIMAL = _ID_ANIMAL);

	ELSEIF _ACAO = 'G' THEN
        CREATE TEMPORARY TABLE GRID_COLUNA(
            ID_COL VARCHAR(100),
            NM_COL VARCHAR(100)
        );

        INSERT INTO GRID_COLUNA(ID_COL, NM_COL)
        VALUES  ('NOME', 'Nome'),
                ('TIPO_ANIMAL', 'Tipo Animal'),
                ('RACA', 'Raça'),
                ('PORTE', 'Porte'),
                ('IDADE', 'Idade'),
                ('DESCRICAO', 'Descrição'),
                ('SEXO', 'Sexo');

        SELECT * FROM GRID_COLUNA;
    END IF;
END