CREATE PROCEDURE `CRUD_ARRECADACAO`(IN jsonData JSON)
BEGIN 
    DECLARE _ACAO CHAR;
    DECLARE _ID_ARRECADACAO INT;
    DECLARE _TITULO VARCHAR(100);
    DECLARE _NOME_ANIMAL VARCHAR(100);
    DECLARE _DESCRICAO VARCHAR(100);
    DECLARE _NOME_USUARIO VARCHAR(100);
    DECLARE _VL_ARRECADACAO INT;
    DECLARE _VL_ARRECADADO INT;
    DECLARE _NM_CONTA VARCHAR(100);
    DECLARE _NU_CONTA INT;
    DECLARE _NU_AGENCIA INT;
    DECLARE _QR_CODE VARCHAR(100);

    DECLARE _CODIGO_ERRO INT;
    DECLARE _ERRO_MSG VARCHAR(255);

    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
    BEGIN
        GET DIAGNOSTICS CONDITION 1
            _CODIGO_ERRO = MYSQL_ERRNO, _ERRO_MSG = MESSAGE_TEXT;

        SET _ERRO_MSG = CONCAT('Erro na linha: ', _CODIGO_ERRO, ' Mensagem: ', _ERRO_MSG);

        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = _ERRO_MSG;
    END;

    SET _ACAO = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.ACAO'));
    SET _ID_ARRECADACAO = CAST(JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.ID_ARRECADACAO')) AS UNSIGNED);
    SET _TITULO = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.TITULO'));
    SET _NOME_ANIMAL = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.NOME_ANIMAL'));
    SET _DESCRICAO = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.DESCRICAO'));
    SET _NOME_USUARIO = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.NOME_USUARIO'));
    SET _VL_ARRECADACAO = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.VL_ARRECADACAO'));
    SET _VL_ARRECADADO = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.VL_ARRECADADO'));
    SET _NM_CONTA = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.NM_CONTA'));
    SET _NU_CONTA = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.NU_CONTA'));
    SET _NU_AGENCIA = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.NU_AGENCIA'));
    SET _QR_CODE = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.QR_CODE'));

    IF _ACAO = 'C' THEN 
        INSERT INTO ARRECADACAO
        (
            TITULO, 
            NOME_ANIMAL, 
            DESCRICAO, 
            NOME_USUARIO, 
            VL_ARRECADACAO, 
            VL_ARRECADADO, 
            NM_CONTA, 
            NU_CONTA, 
            NU_AGENCIA, 
            QR_CODE
        )
        VALUES 
        (
            _TITULO, 
            _NOME_ANIMAL, 
            _DESCRICAO, 
            _NOME_USUARIO, 
            _VL_ARRECADACAO, 
            _VL_ARRECADADO, 
            _NM_CONTA, 
            _NU_CONTA, 
            _NU_AGENCIA, 
            _QR_CODE
        );

    ELSEIF _ACAO = 'U' THEN 
        UPDATE ARRECADACAO SET  
            TITULO = _TITULO,
            NOME_ANIMAL = _NOME_ANIMAL,
            DESCRICAO = _DESCRICAO,
            NOME_USUARIO = _NOME_USUARIO,
            VL_ARRECADACAO = _VL_ARRECADACAO,
            VL_ARRECADADO = _VL_ARRECADADO,
            NM_CONTA = _NM_CONTA,
            NU_CONTA = _NU_CONTA,
            NU_AGENCIA = _NU_AGENCIA,
            QR_CODE = _QR_CODE
        WHERE ID_ARRECADACAO = _ID_ARRECADACAO;

    ELSEIF _ACAO = 'D' THEN 
        DELETE FROM ARRECADACAO 
        WHERE ID_ARRECADACAO = _ID_ARRECADACAO;

    ELSEIF _ACAO = 'R' THEN 
        SELECT * FROM ARRECADACAO 
        WHERE 1 = 1  
            AND (_ID_ARRECADACAO IS NULL OR ID_ARRECADACAO = _ID_ARRECADACAO);
    END IF;
END 