CREATE DEFINER=`root`@`localhost` PROCEDURE `CRUD_ARRECADACAO`(IN jsonData JSON)
BEGIN 
    DECLARE ACAO CHAR;
    DECLARE ID_ARRECADACAO INT;
    DECLARE TITULO VARCHAR(100);
    DECLARE NOME_ANIMAL VARCHAR(100);
    DECLARE DESCRICAO VARCHAR(100);
    DECLARE NOME_USUARIO VARCHAR(100);
    DECLARE VL_ARRECADACAO INT;
    DECLARE VL_ARRECADADO INT;
    DECLARE NM_CONTA VARCHAR(100);
    DECLARE NU_CONTA INT;
    DECLARE NU_AGENCIA INT;
    DECLARE QR_CODE VARCHAR(100);

    SET ACAO = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.ACAO'));
    SET ID_ARRECADACAO = CAST(JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.ID_ARRECADACAO')) AS UNSIGNED);
    SET TITULO = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.TITULO'));
    SET NOME_ANIMAL = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.NOME_ANIMAL'));
    SET DESCRICAO = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.DESCRICAO'));
    SET NOME_USUARIO = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.NOME_USUARIO'));
    SET VL_ARRECADACAO = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.VL_ARRECADACAO'));
    SET VL_ARRECADADO = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.VL_ARRECADADO'));
    SET NM_CONTA = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.NM_CONTA'));
    SET NU_CONTA = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.NU_CONTA'));
    SET NU_AGENCIA = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.NU_AGENCIA'));
    SET QR_CODE = JSON_UNQUOTE(JSON_EXTRACT(jsonData, '$.QR_CODE'));

    IF ACAO = 'C' THEN 
        INSERT INTO ARRECADACAO(TITULO, NOME_ANIMAL, DESCRICAO, NOME_USUARIO, VL_ARRECADACAO, VL_ARRECADADO, NM_CONTA, NU_CONTA, NU_AGENCIA, QR_CODE)
        VALUES (TITULO, NOME_ANIMAL, DESCRICAO, NOME_USUARIO, VL_ARRECADACAO, VL_ARRECADADO, NM_CONTA, NU_CONTA, NU_AGENCIA, QR_CODE);
    ELSEIF ACAO = 'U' THEN 
        UPDATE ARRECADACAO SET  
            TITULO = TITULO,
            NOME_ANIMAL = NOME_ANIMAL,
            DESCRICAO = DESCRICAO,
            NOME_USUARIO = NOME_USUARIO,
            VL_ARRECADACAO = VL_ARRECADACAO,
            VL_ARRECADADO = VL_ARRECADADO,
            NM_CONTA = NM_CONTA,
            NU_CONTA = NU_CONTA,
            NU_AGENCIA = NU_AGENCIA,
            QR_CODE = QR_CODE
        WHERE ID_ARRECADACAO = ID_ARRECADACAO;
    ELSEIF ACAO = 'D' THEN 
        DELETE FROM ARRECADACAO WHERE ID_ARRECADACAO = ID_ARRECADACAO;
    ELSEIF ACAO = 'R' THEN 
        SELECT * FROM ARRECADACAO WHERE ID_ARRECADACAO = ID_ARRECADACAO;
    ELSEIF ACAO = 'S' THEN 
        SELECT * FROM ARRECADACAO;
    END IF;
END 