CREATE DATABASE SOS_PATINHAS;
USE SOS_PATINHAS;


CREATE TABLE TAG (
    ID_TAG INT PRIMARY KEY AUTO_INCREMENT,
    DS_TAG VARCHAR(100)
);

CREATE TABLE ANIMAL (
    ID_ANIMAL INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100),
    TIPO_ANIMAL VARCHAR(100),
    RACA VARCHAR(100),
    PORTE VARCHAR(100),
    IDADE VARCHAR(100),
    DESCRICAO VARCHAR(100),
    SEXO BOOLEAN
);

CREATE TABLE TAG_ANIMAL (
    ID_TAG INT,
    ID_ANIMAL INT,
    FOREIGN KEY (ID_ANIMAL) REFERENCES ANIMAL(ID_ANIMAL),
    FOREIGN KEY (ID_TAG) REFERENCES TAG(ID_TAG)
);

CREATE TABLE FOTO (
    ID_FOTO INT PRIMARY KEY AUTO_INCREMENT,
    ID_TABELA INT,
    NM_TABELA VARCHAR(100), 
    CAMINHO_FOTO VARCHAR(100)
);

CREATE TABLE ARRECADACAO (
    ID_ARRECADACAO INT PRIMARY KEY AUTO_INCREMENT,
    TITULO VARCHAR(100),
    NOME_ANIMAL VARCHAR(100),
    DESCRICAO VARCHAR(100),
    NOME_USUARIO VARCHAR(100),
    VL_ARRECADACAO INT,
    VL_ARRECADADO INT,
    NM_CONTA VARCHAR(100),
    NU_CONTA INT,
    NU_AGENCIA INT,
    QR_CODE VARCHAR(100)
);

CREATE TABLE EVENTO (
    ID_EVENTO INT PRIMARY KEY AUTO_INCREMENT,
    TITULO VARCHAR(100),
    DESCRICAO VARCHAR(100),
    CIDADE_ESTADO VARCHAR(100),
    LOCAL_EVENTO VARCHAR(100)
);

CREATE TABLE MEMBRO_ADM (
    ID_MEMBRO_ADM INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100),
    EMAIL VARCHAR(100),
    TELEFONE VARCHAR(100),
    SENHA VARCHAR(100)
);

CREATE TABLE PERMISSAO (
    ID_PERMISSAO INT PRIMARY KEY AUTO_INCREMENT,
    PAGINA VARCHAR(100)
);

CREATE TABLE PERMISSAO_MEMBRO_ADM (
    ID_PERMISSAO_MEMBRO_ADM INT PRIMARY KEY AUTO_INCREMENT,
    ID_MEMBRO_ADM INT,
    ID_PERMISSAO INT,
    FG_ACESSO BOOLEAN,
    FOREIGN KEY (ID_MEMBRO_ADM) REFERENCES MEMBRO_ADM(ID_MEMBRO_ADM),
    FOREIGN KEY (ID_PERMISSAO) REFERENCES PERMISSAO(ID_PERMISSAO)
);

CREATE TABLE USUARIO (
    ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100),
    CPF VARCHAR(100),
    RG VARCHAR(100), -- Fixed syntax
    EMAIL VARCHAR(100),
    DATA_NASCIMENTO DATE,
    TELEFONE VARCHAR(100),
    SENHA VARCHAR(100)
);

CREATE TABLE PARTE_EDITAVEL (
    ID_PARTE_EDITAVEL VARCHAR(100),
    INPUT_SIMPLES VARCHAR(100),
    TEXTAREA VARCHAR(100),
    CAMINHO_IMAGEM VARCHAR(100)
);

CREATE TABLE FORMULARIO_PERGUNTA (
    ID_FORMULARIO_PERGUNTA INT PRIMARY KEY AUTO_INCREMENT,
    DS_FORMULARIO_PERGUNTA VARCHAR(100)
);

CREATE TABLE FORMULARIO_PERGUNTA_RESPOSTA (
    ID_FORMULARIO_RESPOSTA INT PRIMARY KEY AUTO_INCREMENT,
    ID_FORMULARIO_PERGUNTA INT,
    DS_FORMULARIO_RESPOSTA VARCHAR(100),
    FOREIGN KEY (ID_FORMULARIO_PERGUNTA) REFERENCES FORMULARIO_PERGUNTA(ID_FORMULARIO_PERGUNTA)
);

CREATE TABLE FORMULARIO_RELATORIO (
    ID_FORMULARIO_RELATORIO INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT,
    ID_ANIMAL INT,
    ID_FORMULARIO_PERGUNTA_RESPOSTA INT,
    CIDADE VARCHAR(100),
    ESTADO VARCHAR(100),
    RUA VARCHAR(100),
    NU_RUA INT,
    BAIRRO VARCHAR(100),
    COMPLEMENTO VARCHAR(100),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_ANIMAL) REFERENCES ANIMAL(ID_ANIMAL),
    FOREIGN KEY (ID_FORMULARIO_PERGUNTA_RESPOSTA) REFERENCES FORMULARIO_PERGUNTA_RESPOSTA(ID_FORMULARIO_RESPOSTA)
);

CREATE TABLE FORMULARIO_CRIAR_EDITAR(
    ID_FORMULARIO_CRIAR_EDITAR INT PRIMARY KEY AUTO_INCREMENT,
    ID_FORM VARCHAR(100),
    NAME VARCHAR(100),
    PLACEHOLDER VARCHAR(100),
    TIPO VARCHAR(100),
    OBRIGATORIO BOOLEAN
);
